version: "3.8"

services:
  webapp:
    build: .
    container_name: rust_webapp
    ports:
      - "3005:8080"
    privileged: true
    environment:
      WASMIOT_ORCHESTRATOR_URL: "${WASMIOT_ORCHESTRATOR_URL}"
      DEVICE_TYPE: RaspberryPi-with-camera
      SUPERVISOR_NAME: rust-port # TODO: Does this become the supervisors name in the orchestrator??
      WASMIOT_SUPERVISOR_IP: "172.15.0.25"
      WASMIOT_SUPERVISOR_PORT: "8080"
      DEFAULT_URL_SCHEME: "http"
    volumes:
      - ./instance/configs:/app/instance/configs
      - ./instance/modules:/app/instance/modules
      - ./instance/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.25
    # TODO: Enable later
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 30s

networks:
  default:
    external: true
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24

# networks:
#   wasmiot-net:
#     external: true
#     ipv4_address: 172.15.0.50



#       # Supervisor Base Service
#   device-base:
#     profiles:
#       - ABSTRACT_BASE_HACK_DO_NOT_USE
#     image: ghcr.io/liquidai-project/wasmiot-supervisor
#     volumes:
#       - type: bind
#         source: ./wasmiot-supervisor/host_app
#         target: /app/host_app
#     env_file:
#       - .env
#     # links:
#     #   - orchestrator
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
#       interval: 1m30s
#       timeout: 30s
#       retries: 3
#       start_period: 30s



  # raspi1:
  #   extends: device-base
  #   profiles:
  #     - device
  #   environment:
  #     - DEVICE_TYPE=RaspberryPi-with-camera
  #     - FLASK_APP=raspi1
  #     - WASMIOT_SUPERVISOR_IP=172.15.0.21
  #   ports:
  #     - 3001:5000
  #   privileged: true
  #   volumes:
  #     - ./devices/raspi1/configs:/app/instance/configs
  #     - ./devices/raspi1/modules:/app/instance/modules
  #     - ./devices/raspi1/output:/app/instance/output
  #   networks:
  #     default:
  #       ipv4_address: 172.15.0.21